# This is a basic workflow to help you get started with Actions

name: fetch-data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tradein-space:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: fetch tradein.space/GameData.json
        run: curl --fail https://tradein.space/api/data/GameData > tradein.space/GameData.json

      - name: Extract version from GameData.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: echo PU_VERSION='jq .Name tradein.space/GameData.json -r' >> $GITHUB_OUTPUT

      - name: save file
        uses: EndBug/add-and-commit@v9
        with:
          add: tradein.space/*.json
          message: 'update GameData ${{ steps.pu_version.outputs.pu_version }}'

#      - name: tag is commited
#        uses: EndBug/add-and-commit@v9
#        with:
#          tag: tradein-space-${{ steps.pu_version.outputs.pu_version }}

  fleetyard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: fleetyards/models 
        run: curl --fail "https://api.fleetyards.net/v1/models?page=1&perPage=200" > fleetyard.net/models.json

      - name: Get PU version from fleetyard
        id: version
        run: |
          curl --fail https://fleetyards.fra1.digitaloceanspaces.com/sc_data/version > /tmp/version
          echo PU_VERSION='cat /tmp/version' >> $GITHUB_OUTPUT

      - name: save file
        uses: EndBug/add-and-commit@v9
        with:
          add: fleetyard.net/*.json
          message: 'update models ${{ steps.pu_version.outputs.pu_version }}'
 
#      - name: tag is commited
#        uses: EndBug/add-and-commit@v9
#        with:
#          tag: fleetyard-net-${{ steps.pu_version.outputs.pu_version }}

  extraction-locations:
    runs-on: ubuntu-latest
    needs: [tradein-space, fleetyard]
    steps:
      - uses: actions/checkout@v3

      - name: Extraction process
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python $GITHUB_WORKSPACE/extraction.py -i $GITHUB_WORKSPACE/tradein.space/GameData.json
     
      - name: Format to csv
        uses: sergeysova/jq-action@v2
        with:
          cmd: cat fleetyard.net/models.json | jq -r ".[] | [.name, .cargo] | @csv" > nargit/models.csv

      - name: save files
        uses: EndBug/add-and-commit@v9
        with:
          add: nargit/*
          message: 'Update nargit data'

