# This is a basic workflow to help you get started with Actions

name: fetch-data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tradein-space:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: fetch tradein.space/GameData.json
        run: curl https://tradein.space/api/data/GameData -o tradein.space/GameData.json

      - name: Extract version from GameData.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .Name tradein.space/GameData.json -r'

      - name: Extract SystemLocations
        uses: sergeysova/jq-action@v2
        id: system-locations
        with:
          cmd: 'jq .SystemLocations tradein.space/GameData.json -r -c'

      - name: create file SystemLocations.json
        run: echo ${{ steps.system-locations.outputs.value }} > tradein.space/SystemLocations.json

      - name: save file and tag
        uses: EndBug/add-and-commit@v9
        with:
          add: tradein.space/*.json
          message: 'update GameData'
          tag: ${{ steps.version.outputs.value }}
