name: flat-fleetyards
on:
  workflow_dispatch:
  push:
    tags-ignore:
     - .*
    paths:
      - .github/workflows/flat-fleetyards.yaml
      - fleetyards.net/postprocessing.ts
jobs:
  flat:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.fleetyards.net/v1/models?page=1&perPage=240
          downloaded_filename: fleetyards.net/models.json
          postprocess: ./fleetyards.net/postprocessing.ts
