# This is a basic workflow to help you get started with Actions

name: fetch-fleet-yards

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fleetyards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: fleetyards/models
        run: curl --fail "https://api.fleetyards.net/v1/models?page=1&perPage=200" > fleetyard.net/models.json

      - name: Get PU version from fleetyard
        id: version
        run: |
          curl --fail https://fleetyards.fra1.digitaloceanspaces.com/sc_data/version > /tmp/version
          echo PU_VERSION='cat /tmp/version' >> $GITHUB_OUTPUT

      - name: save file
        uses: EndBug/add-and-commit@v9
        with:
          add: fleetyard.net/*.json
          message: 'update models ${{ steps.pu_version.outputs.pu_version }}'
  
  extraction-locations:
    runs-on: ubuntu-latest
    needs: [ fleetyards ]
    steps:
      - uses: actions/checkout@v3

      - name: Format to csv
        uses: sergeysova/jq-action@v2
        with:
          cmd: cat fleetyard.net/models.json | jq -r ".[] | [.name, .cargo] | @csv" > nargit/models.csv

      - name: save files
        uses: EndBug/add-and-commit@v9
        with:
          add: nargit/*
          message: 'Update fleetyards data'

